# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160130_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.URLField(blank=True),
        ),
    ]
